# Generated by Django 4.1.6 on 2023-02-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alvo', '0002_remove_alvo_id_alter_alvo_identificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alvo',
            name='data_expiracao',
            field=models.DateField(),
        ),
    ]
